import { z } from "zod";

export const WorkerEnvSchema = z.object({
  DATABASE_URL: z.string().min(1),
  SUPABASE_URL: z.string().url(),
  SUPABASE_SECRET_KEY: z.string().min(1),
  DAYTONA_API_KEY: z.string().min(1).optional(),
  DAYTONA_API_URL: z.string().url().optional(),
  DAYTONA_ANALYTICS_API_URL: z.string().url().optional(),
  DAYTONA_TARGET: z.string().min(1).optional(),
  E2B_API_KEY: z.string().min(1).optional(),
  E2B_API_URL: z.string().url().optional(),
  E2B_TEMPLATE_ID: z.string().min(1).optional(),
  MODAL_TOKEN_ID: z.string().min(1).optional(),
  MODAL_TOKEN_SECRET: z.string().min(1).optional(),
  MODAL_TOKEN_PROFILE: z.string().min(1).optional(),
  MODAL_ENVIRONMENT: z.string().min(1).optional(),
  MODAL_APP_NAME: z.string().min(1).optional(),
  LOG_LEVEL: z.string().default("info"),
  METAL_ENVIRONMENT: z.string().default("development"),
  WORKER_ID: z.string().min(1),
  WORKER_LEASE_MS: z.coerce.number().int().min(1000).default(30_000),
  WORKER_POLL_MS: z.coerce.number().int().min(50).default(250),
  WORKER_BATCH_SIZE: z.coerce.number().int().min(1).max(100).default(10),
  WORKER_MAX_ATTEMPTS: z.coerce.number().int().min(1).default(8),
  WORKER_BASE_BACKOFF_MS: z.coerce.number().int().min(1).default(200),
});
export type WorkerEnv = z.infer<typeof WorkerEnvSchema>;

export function loadWorkerEnv(source: NodeJS.ProcessEnv = process.env): WorkerEnv {
  return WorkerEnvSchema.parse({
    DATABASE_URL: source.DATABASE_URL,
    SUPABASE_URL: source.SUPABASE_URL,
    SUPABASE_SECRET_KEY: source.SUPABASE_SECRET_KEY,
    DAYTONA_API_KEY: source.DAYTONA_API_KEY,
    DAYTONA_API_URL: source.DAYTONA_API_URL,
    DAYTONA_ANALYTICS_API_URL: source.DAYTONA_ANALYTICS_API_URL,
    DAYTONA_TARGET: source.DAYTONA_TARGET,
    E2B_API_KEY: source.E2B_API_KEY,
    E2B_API_URL: source.E2B_API_URL,
    E2B_TEMPLATE_ID: source.E2B_TEMPLATE_ID,
    MODAL_TOKEN_ID: source.MODAL_TOKEN_ID,
    MODAL_TOKEN_SECRET: source.MODAL_TOKEN_SECRET,
    MODAL_TOKEN_PROFILE: source.MODAL_TOKEN_PROFILE,
    MODAL_ENVIRONMENT: source.MODAL_ENVIRONMENT,
    MODAL_APP_NAME: source.MODAL_APP_NAME,
    LOG_LEVEL: source.LOG_LEVEL,
    METAL_ENVIRONMENT: source.METAL_ENVIRONMENT,
    WORKER_ID: source.WORKER_ID,
    WORKER_LEASE_MS: source.WORKER_LEASE_MS,
    WORKER_POLL_MS: source.WORKER_POLL_MS,
    WORKER_BATCH_SIZE: source.WORKER_BATCH_SIZE,
    WORKER_MAX_ATTEMPTS: source.WORKER_MAX_ATTEMPTS,
    WORKER_BASE_BACKOFF_MS: source.WORKER_BASE_BACKOFF_MS,
  });
}
