import { z } from "zod";

export const WorkerEnvSchema = z.object({
  DATABASE_URL: z.string().min(1),
  SUPABASE_URL: z.string().url(),
  SUPABASE_SECRET_KEY: z.string().min(1),
  BL_API_KEY: z.string().min(1).optional(),
  BL_WORKSPACE: z.string().min(1).optional(),
  BLAXEL_API_KEY: z.string().min(1).optional(),
  BLAXEL_WORKSPACE: z.string().min(1).optional(),
  BLAXEL_ACCOUNT_ID: z.string().min(1).optional(),
  BLAXEL_API_URL: z.string().url().optional(),
  BLAXEL_REGION: z.string().min(1).optional(),
  BLAXEL_DEFAULT_IMAGE: z.string().min(1).optional(),
  BLAXEL_DEFAULT_MEMORY_MB: z.coerce.number().int().min(512).optional(),
  NORTHFLANK_API_TOKEN: z.string().min(1).optional(),
  NORTHFLANK_PROJECT_ID: z.string().min(1).optional(),
  NORTHFLANK_TEAM_ID: z.string().min(1).optional(),
  NORTHFLANK_API_URL: z.string().url().optional(),
  NORTHFLANK_DEPLOYMENT_PLAN: z.string().min(1).optional(),
  NORTHFLANK_DEFAULT_IMAGE: z.string().min(1).optional(),
  NORTHFLANK_EPHEMERAL_STORAGE_MB: z.coerce.number().int().min(1_024).optional(),
  RUNLOOP_API_KEY: z.string().min(1).optional(),
  RUNLOOP_API_URL: z.string().url().optional(),
  RUNLOOP_RESOURCE_SIZE: z
    .enum(["X_SMALL", "SMALL", "MEDIUM", "LARGE", "X_LARGE", "XX_LARGE"])
    .optional(),
  RUNLOOP_BLUEPRINT_ID: z.string().min(1).optional(),
  RUNLOOP_VCPU_HOUR_RATE_USD: z.coerce.number().nonnegative().optional(),
  RUNLOOP_MEMORY_GB_HOUR_RATE_USD: z.coerce.number().nonnegative().optional(),
  RUNLOOP_DISK_GB_HOUR_RATE_USD: z.coerce.number().nonnegative().optional(),
  CODESANDBOX_API_KEY: z.string().min(1).optional(),
  CODESANDBOX_API_URL: z.string().url().optional(),
  CODESANDBOX_TEMPLATE_ID: z.string().min(1).optional(),
  CODESANDBOX_VM_TIER: z
    .enum(["Pico", "Nano", "Micro", "Small", "Medium", "Large", "XLarge"])
    .optional(),
  CODESANDBOX_WORKSPACE_ID: z.string().min(1).optional(),
  CODESANDBOX_CREDIT_RATE_USD: z.coerce.number().nonnegative().optional(),
  DAYTONA_API_KEY: z.string().min(1).optional(),
  DAYTONA_API_URL: z.string().url().optional(),
  DAYTONA_ANALYTICS_API_URL: z.string().url().optional(),
  DAYTONA_TARGET: z.string().min(1).optional(),
  DAYTONA_PAUSE_SUPPORTED: z
    .enum(["true", "false"])
    .transform((value) => value === "true")
    .optional(),
  CLOUDFLARE_SANDBOX_API_URL: z.string().url().optional(),
  CLOUDFLARE_SANDBOX_API_KEY: z.string().min(1).optional(),
  CLOUDFLARE_ACCOUNT_ID: z.string().min(1).optional(),
  CLOUDFLARE_ANALYTICS_API_TOKEN: z.string().min(1).optional(),
  E2B_API_KEY: z.string().min(1).optional(),
  E2B_API_URL: z.string().url().optional(),
  E2B_TEMPLATE_ID: z.string().min(1).optional(),
  MODAL_TOKEN_ID: z.string().min(1).optional(),
  MODAL_TOKEN_SECRET: z.string().min(1).optional(),
  MODAL_TOKEN_PROFILE: z.string().min(1).optional(),
  MODAL_ENVIRONMENT: z.string().min(1).optional(),
  MODAL_APP_NAME: z.string().min(1).optional(),
  VERCEL_OIDC_TOKEN: z.string().min(1).optional(),
  VERCEL_TOKEN: z.string().min(1).optional(),
  VERCEL_TEAM_ID: z.string().min(1).optional(),
  VERCEL_PROJECT_ID: z.string().min(1).optional(),
  VERCEL_API_URL: z.string().url().optional(),
  LOG_LEVEL: z.string().default("info"),
  METAL_ENVIRONMENT: z.string().default("development"),
  WORKER_ID: z.string().min(1),
  WORKER_LEASE_MS: z.coerce.number().int().min(1000).default(30_000),
  WORKER_POLL_MS: z.coerce.number().int().min(50).default(250),
  WORKER_BATCH_SIZE: z.coerce.number().int().min(1).max(100).default(10),
  WORKER_MAX_ATTEMPTS: z.coerce.number().int().min(1).default(8),
  WORKER_BASE_BACKOFF_MS: z.coerce.number().int().min(1).default(200),
  WORKER_COST_SWEEP_MS: z.coerce
    .number()
    .int()
    .min(60_000)
    .default(5 * 60_000),
  STRIPE_SECRET_KEY: z.string().min(1).optional(),
});
export type WorkerEnv = z.infer<typeof WorkerEnvSchema>;

export function loadWorkerEnv(source: NodeJS.ProcessEnv = process.env): WorkerEnv {
  return WorkerEnvSchema.parse({
    DATABASE_URL: source.DATABASE_URL,
    SUPABASE_URL: source.SUPABASE_URL,
    SUPABASE_SECRET_KEY: source.SUPABASE_SECRET_KEY,
    BL_API_KEY: source.BL_API_KEY,
    BL_WORKSPACE: source.BL_WORKSPACE,
    BLAXEL_API_KEY: source.BLAXEL_API_KEY,
    BLAXEL_WORKSPACE: source.BLAXEL_WORKSPACE,
    BLAXEL_ACCOUNT_ID: source.BLAXEL_ACCOUNT_ID,
    BLAXEL_API_URL: source.BLAXEL_API_URL,
    BLAXEL_REGION: source.BLAXEL_REGION,
    BLAXEL_DEFAULT_IMAGE: source.BLAXEL_DEFAULT_IMAGE,
    BLAXEL_DEFAULT_MEMORY_MB: source.BLAXEL_DEFAULT_MEMORY_MB,
    NORTHFLANK_API_TOKEN: source.NORTHFLANK_API_TOKEN,
    NORTHFLANK_PROJECT_ID: source.NORTHFLANK_PROJECT_ID,
    NORTHFLANK_TEAM_ID: source.NORTHFLANK_TEAM_ID,
    NORTHFLANK_API_URL: source.NORTHFLANK_API_URL,
    NORTHFLANK_DEPLOYMENT_PLAN: source.NORTHFLANK_DEPLOYMENT_PLAN,
    NORTHFLANK_DEFAULT_IMAGE: source.NORTHFLANK_DEFAULT_IMAGE,
    NORTHFLANK_EPHEMERAL_STORAGE_MB: source.NORTHFLANK_EPHEMERAL_STORAGE_MB,
    RUNLOOP_API_KEY: source.RUNLOOP_API_KEY,
    RUNLOOP_API_URL: source.RUNLOOP_API_URL,
    RUNLOOP_RESOURCE_SIZE: source.RUNLOOP_RESOURCE_SIZE,
    RUNLOOP_BLUEPRINT_ID: source.RUNLOOP_BLUEPRINT_ID,
    RUNLOOP_VCPU_HOUR_RATE_USD: source.RUNLOOP_VCPU_HOUR_RATE_USD,
    RUNLOOP_MEMORY_GB_HOUR_RATE_USD: source.RUNLOOP_MEMORY_GB_HOUR_RATE_USD,
    RUNLOOP_DISK_GB_HOUR_RATE_USD: source.RUNLOOP_DISK_GB_HOUR_RATE_USD,
    CODESANDBOX_API_KEY: source.CODESANDBOX_API_KEY,
    CODESANDBOX_API_URL: source.CODESANDBOX_API_URL,
    CODESANDBOX_TEMPLATE_ID: source.CODESANDBOX_TEMPLATE_ID,
    CODESANDBOX_VM_TIER: source.CODESANDBOX_VM_TIER,
    CODESANDBOX_WORKSPACE_ID: source.CODESANDBOX_WORKSPACE_ID,
    CODESANDBOX_CREDIT_RATE_USD: source.CODESANDBOX_CREDIT_RATE_USD,
    DAYTONA_API_KEY: source.DAYTONA_API_KEY,
    DAYTONA_API_URL: source.DAYTONA_API_URL,
    DAYTONA_ANALYTICS_API_URL: source.DAYTONA_ANALYTICS_API_URL,
    DAYTONA_TARGET: source.DAYTONA_TARGET,
    DAYTONA_PAUSE_SUPPORTED: source.DAYTONA_PAUSE_SUPPORTED,
    CLOUDFLARE_SANDBOX_API_URL: source.CLOUDFLARE_SANDBOX_API_URL,
    CLOUDFLARE_SANDBOX_API_KEY: source.CLOUDFLARE_SANDBOX_API_KEY,
    CLOUDFLARE_ACCOUNT_ID: source.CLOUDFLARE_ACCOUNT_ID,
    CLOUDFLARE_ANALYTICS_API_TOKEN: source.CLOUDFLARE_ANALYTICS_API_TOKEN,
    E2B_API_KEY: source.E2B_API_KEY,
    E2B_API_URL: source.E2B_API_URL,
    E2B_TEMPLATE_ID: source.E2B_TEMPLATE_ID,
    MODAL_TOKEN_ID: source.MODAL_TOKEN_ID,
    MODAL_TOKEN_SECRET: source.MODAL_TOKEN_SECRET,
    MODAL_TOKEN_PROFILE: source.MODAL_TOKEN_PROFILE,
    MODAL_ENVIRONMENT: source.MODAL_ENVIRONMENT,
    MODAL_APP_NAME: source.MODAL_APP_NAME,
    VERCEL_OIDC_TOKEN: source.VERCEL_OIDC_TOKEN,
    VERCEL_TOKEN: source.VERCEL_TOKEN,
    VERCEL_TEAM_ID: source.VERCEL_TEAM_ID,
    VERCEL_PROJECT_ID: source.VERCEL_PROJECT_ID,
    VERCEL_API_URL: source.VERCEL_API_URL,
    LOG_LEVEL: source.LOG_LEVEL,
    METAL_ENVIRONMENT: source.METAL_ENVIRONMENT,
    WORKER_ID: source.WORKER_ID,
    WORKER_LEASE_MS: source.WORKER_LEASE_MS,
    WORKER_POLL_MS: source.WORKER_POLL_MS,
    WORKER_BATCH_SIZE: source.WORKER_BATCH_SIZE,
    WORKER_MAX_ATTEMPTS: source.WORKER_MAX_ATTEMPTS,
    WORKER_BASE_BACKOFF_MS: source.WORKER_BASE_BACKOFF_MS,
    WORKER_COST_SWEEP_MS: source.WORKER_COST_SWEEP_MS,
    STRIPE_SECRET_KEY: source.STRIPE_SECRET_KEY,
  });
}
